// Korean Names for Top stocks
export const TOP_STOCKS = {
    KOSPI: [
        { symbol: '005930', name: '삼성전자' },
        { symbol: '000660', name: 'SK하이닉스' },
        { symbol: '373220', name: 'LG에너지솔루션' },
        { symbol: '207940', name: '삼성바이오로직스' },
        { symbol: '005380', name: '현대차' },
        // ... (existing)
        { symbol: '022100', name: '포스코DX' }, // Moved from KOSDAQ
        { symbol: '066970', name: '엘앤에프' }, // Moved from KOSDAQ
    ],
    KOSDAQ: [
        { symbol: '247540', name: '에코프로비엠' },
        { symbol: '086520', name: '에코프로' },
        { symbol: '196170', name: '알테오젠' },
        { symbol: '028300', name: 'HLB' },
        { symbol: '293490', name: '카카오게임즈' },
        { symbol: '035900', name: 'JYP Ent.' },
        { symbol: '403870', name: 'HPSP' },
        { symbol: '277810', name: '레인보우로보틱스' },
        { symbol: '058470', name: '리노공업' },
        { symbol: '215000', name: '골프존' },
        { symbol: '263750', name: '펄어비스' },
        { symbol: '214150', name: '클래시스' },
        { symbol: '041510', name: '에스엠' },
        { symbol: '112040', name: '위메이드' },
        { symbol: '005290', name: '동진쎄미켐' },
        { symbol: '039030', name: '이오테크닉스' },
        { symbol: '237690', name: '강원랜드' },
        { symbol: '034230', name: '파라다이스' },
        { symbol: '145020', name: '휴젤' },
        { symbol: '253450', name: '스튜디오드래곤' },
        { symbol: '035760', name: 'CJ ENM' },
        { symbol: '095610', name: '테스' },
        { symbol: '068240', name: '다원시스' }
    ],
    SP500: [
        { symbol: 'AAPL', name: '애플' },
        { symbol: 'MSFT', name: '마이크로소프트' },
        { symbol: 'GOOGL', name: '알파벳 A (구글)' },
        { symbol: 'AMZN', name: '아마존' },
        { symbol: 'NVDA', name: '엔비디아' },
        { symbol: 'META', name: '메타 (페이스북)' },
        { symbol: 'TSLA', name: '테슬라' },
        { symbol: 'BRK.B', name: '버크셔 해서웨이 B' },
        { symbol: 'LLY', name: '일라이 릴리' },
        { symbol: 'V', name: '비자' },
        { symbol: 'TSM', name: 'TSMC' },
        { symbol: 'JPM', name: 'JP모건 체이스' },
        { symbol: 'UNH', name: '유나이티드헬스' },
        { symbol: 'MC', name: 'LVMH' },
        { symbol: 'XOM', name: '엑슨모빌' },
        { symbol: 'JNJ', name: '존슨앤존슨' },
        { symbol: 'WMT', name: '월마트' },
        { symbol: 'PG', name: 'P&G' },
        { symbol: 'MA', name: '마스터카드' },
        { symbol: 'AVGO', name: '브로드컴' },
        { symbol: 'HD', name: '홈디포' },
        { symbol: 'CVX', name: '쉐브론' },
        { symbol: 'MRK', name: '머크' },
        { symbol: 'KO', name: '코카콜라' },
        { symbol: 'ABBV', name: '애브비' },
        { symbol: 'PEP', name: '펩시코' },
        { symbol: 'COST', name: '코스트코' },
        { symbol: 'BAC', name: '뱅크오브아메리카' },
        { symbol: 'ADBE', name: '어도비' },
        { symbol: 'CRM', name: '세일즈포스' }
    ],
    NASDAQ: [
        { symbol: 'AAPL', name: '애플' },
        { symbol: 'MSFT', name: '마이크로소프트' },
        { symbol: 'GOOGL', name: '알파벳 A' },
        { symbol: 'AMZN', name: '아마존' },
        { symbol: 'NVDA', name: '엔비디아' },
        { symbol: 'META', name: '메타' },
        { symbol: 'TSLA', name: '테슬라' },
        { symbol: 'GOOG', name: '알파벳 C' },
        { symbol: 'AVGO', name: '브로드컴' },
        { symbol: 'PEP', name: '펩시코' },
        { symbol: 'COST', name: '코스트코' },
        { symbol: 'CSCO', name: '시스코' },
        { symbol: 'TMUS', name: 'T-모바일' },
        { symbol: 'ADBE', name: '어도비' },
        { symbol: 'TXN', name: '텍사스 인스트루먼트' },
        { symbol: 'NFLX', name: '넷플릭스' },
        { symbol: 'AMD', name: 'AMD' },
        { symbol: 'QCOM', name: '퀄컴' },
        { symbol: 'INTC', name: '인텔' },
        { symbol: 'HON', name: '하니웰' },
        { symbol: 'AMGN', name: '암젠' },
        { symbol: 'INTU', name: '인튜이트' },
        { symbol: 'SBUX', name: '스타벅스' },
        { symbol: 'MDLZ', name: '몬델리즈' },
        { symbol: 'GILD', name: '길리어드 사이언스' },
        { symbol: 'BKNG', name: '부킹 홀딩스' },
        { symbol: 'ISRG', name: '인튜이티브 서지컬' },
        { symbol: 'ADI', name: '아나로그디바이스' },
        { symbol: 'VRTX', name: '버텍스' },
        { symbol: 'REGN', name: '리제네론' }
    ]
}
